### ISSUE TITLE
set_ssds.pl appends '/' to data_files.txt

### ISSUE THREAD

**Issue by pavjav** [flashxio/FlashX#228]
issue causes safs-util to run into errors
by issuing a second slash:
/mnt/ssd1//lost+found doesn't have exactly one file
lost+found is corrupted

**Comment by zheng-da** [comment]
It's fine to have '//' in the path.
It seems to me that you give "/mnt/ssd1" as a data directory for SAFS. If so, all files/directories in "/mnt/ssd1" should be managed by SAFS.
lost+found is created by the local filesystem, instead of SAFS.

One option is to delete lost+found.
Another option is to use a subdirectory such as "/mnt/ssd1/data" as a data directory for SAFS.

Please let me know if this can help.

**Comment by pavjav** [comment]
I see. I assumed this was causing the problem. I tried making a new
directory and it fixed the problem. Thank you!
