### ISSUE TITLE
Questions on the implementation of WCC.

### ISSUE THREAD

**Issue by dreamedcheng** [flashxio/FlashX#339]
Hi, 
    I found that the implementation of WCC in flashgraph requires to access both in and out-edge lists, can it be implemented by just accessing one type of edge lists, which can save a lot of I/Os on edge data. By the way, if WCC can be implemented by accessing one type of edge lists, will it converge slower than that accessing both edge lists?

**Comment by zheng-da** [comment]
if we only access one type of the edges, I don't think the algorithm will output the same result on a directed graph.
actually, WCC is implemented for directed graphs. We have a CC implementation, which is written for undirected graph. Because there is only one type of edges, CC only need to access one edge for each neighbor.

**Comment by dreamedcheng** [comment]
Right, but I just ran CC on the graph twitter, and found that there is a negligible difference in terms of runtime and the total bytes accessed compared with WCC.  It seems weird, what's wrong with that?

**Comment by zheng-da** [comment]
CC assumes the graph is an undirected graph. but twitter is a directed graph. The newer version (in the dev branch) won't allow you to run CC on a directed graph.

Because CC assumes the input graph is undirected, it only uses one type of the edge. WCC assumes a directed graph, so it uses both types of edges. This also addresses your original question.

**Comment by dreamedcheng** [comment]
Yes, but can I treat twitter as a undirected graph, and convert it to a fg format by using el2fg with -u option, in this way CC can run on it.

**Comment by zheng-da** [comment]
Yes, you can. When you convert a directed graph to an undirected graph, you should use -U option to remove all possible redundant edges.

**Comment by dreamedcheng** [comment]
As you said, I converted twitter to an undirected graph and using -U to remove all possible redundant edges, but the runtime of CC is closed to WCC, as well as the total accessed bytes, which should be half of WCC, since WCC will access two types of edges.

**Comment by zheng-da** [comment]
This depends on the graph. If you have the directed graph A as follows:
a -> b
b -> c
c -> a
To convert this graph to an undirected graph A', it becomes
a - b
b - c
a - c
In other words, converting a directed graph to an undirected graph doesn't reduce the number of edges.

If you run WCC on graph A and CC on graph A', information will be propagated in exactly the same way:
a sends data to b and c, b sends to a and c, c sends to b and a.

If you run WCC on graph A and only use out edges, information propagation will be like this:
a sends data to b, b sends to c and c sends to a

**Comment by dreamedcheng** [comment]
I am clear, thank you!
