### ISSUE TITLE
eigensolver can't converge when computing a few more eigenvalues on some graphs

### ISSUE THREAD

**Issue by zheng-da** [flashxio/FlashX#75]

**Comment by jovo** [comment]
conroy or tamas budvari might be able to help with that.  do you know tamas?

**Comment by zheng-da** [comment]
I don't think I know tamas budvari. Let me look into the problem deeper and find the question I want to ask first.

**Comment by jovo** [comment]
he is AMS faculty, worked with alex for years.
he'd be very excited to get involved i think,
and very useful from a numerical linear algebra perspective, since that is
what he does :))

On Fri, Jan 9, 2015 at 9:30 AM, Da Zheng notifications@github.com wrote:

>  I don't think I know tamas budvari. Let me look into the problem deeper
> and find the question I want to ask first.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashGraph/issues/75#issuecomment-69340606.

## 

it's our dream
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
I think I might have met him before. I'll talk to them once I have my question.

**Comment by zheng-da** [comment]
We will no longer make effort to improve the implementation of this eigensolver.
We'll be able to provide an eigensolver after we port Trilinos to our framework.
